name: exposure
version: 1.0.4
description: >
  Sensor widget for flutter that notifies you when it is exposured
homepage: https://github.com/northka/exposure
dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  pedantic: ^1.11.0
  flutter_test:
    sdk: flutter
environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.5.4-hotfix.2 <2.0.0"